[package]
name = "luminal-handler"
version = "0.0.1"
authors = ["Thomas Gideon <cmdln@thecommandline.net>"]

[dependencies]
error-chain = "0.11"
futures = "0.1"
hyper = "0.11"

[dev-dependencies]
tokio-core = "0.1"
